UniversityofLouisvilleVaccine/Controllers/Grant2Controller.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityofLouisvilleVaccine.Controllers
{
    public class Grant2Controller : Controller
    {
        public ActionResult Index()
        {
            string[] dirs = Directory.GetFiles(AppDomain.CurrentDomain.BaseDirectory + @"FileUploads\", "*.*");
            return View(dirs.ToList());
        }

        [HttpPost]
        
        public ActionResult UploadToAppServer()
        {
            for (int i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase hpf = Request.Files[i];
                if (hpf.ContentLength == 0)
                    continue;

                string savedFileName = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory + "FileUploads/",
                Path.GetFileName(hpf.FileName));
                hpf.SaveAs(savedFileName);
            }
            return RedirectToAction("Index");
        }

        public FileStreamResult StreamFileFromAppServer(string fileNameWithExtention)
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "FileUploads/";
            string fileName = fileNameWithExtention;
            return File(new FileStream(path + fileName, FileMode.Open), "text/plain", fileName);
        }

        public FilePathResult DownloadFileFromAppServer(string fileNameWithExtention)
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "FileUploads/";
            string fileName = fileNameWithExtention;
            return File(path + fileName, "text/plain", "test.txt");
        }
    }
}

UniversityofLouisvilleVaccine/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityofLouisvilleVaccine.Controllers
{
    public class UploadFileController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = System.IO.Path.GetFileName(file.FileName);
                    var path = System.IO.Path.Combine(Server.MapPath("~/FileUploads"), fileName);
                    file.SaveAs(path);
                }
                ViewBag.Message = "Upload successful";
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Message = "Upload failed";
                return RedirectToAction("Index");
            }
        }
    }
}

UniversityofLouisvilleVaccine/Views/UploadFile/Index.cshtml
@using (Html.BeginForm("Upload", "UploadFile", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <div class="jumbotron">
            <h1>Upload Files</h1>
            <br />
            <li>@Html.ActionLink("List Of Uploaded Files", "Index", "Grant2")</li>
            <br />
            <div class="editor-field">
                @Html.TextBox("file", "", new { type = "file" })
            </div>
            <br />
            <div class="editor-field">
                <input type="submit" value="Upload" />
            </div>
            </div>
</fieldset>
}

UniversityofLouisvilleVaccine/Views/UploadFile/Upload.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>